
import Link from 'next/link'
import PressCenterItems from '@/Components/PressCenterItems'


export const metadata = {
  title: 'ანონსები',
  description: 'Generated by Goga',
}
export default async function anonsebiPage() {
  return (
    <>
    <PressCenterItems id='3'/>
    </>
  )
  }
