
import Link from 'next/link'
import PressCenterItems from '@/Components/PressCenterItems'


export const metadata = {
  title: 'განცხადებები',
  description: 'Generated by Goga',
}
export default async function ganckhadebebiPage() {
  return (
    <>
    <PressCenterItems id='2'/>
    </>
  )
  }
