

import Link from 'next/link'
import PressCenterItems from '@/Components/PressCenterItems'


export const metadata = {
  title: 'ვიდეო გალერეა',
  description: 'Generated by Proservice',
}
export default async function NewsPage() {
  return (
    <>
    <PressCenterItems id='5'/>
    </>
  )
  }