
import Link from 'next/link'
import PressCenterItems from '@/Components/PressCenterItems'


export const metadata = {
  title: 'პრესრელიზები',
  description: 'Generated by Goga',
}
export default async function PressReleasesPage() {
  return (
    <>
    <PressCenterItems id='4'/>
    </>
  )
  }